# Generated by Django 4.2.2 on 2023-06-25 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('fotograf', models.ImageField(upload_to='fotograflar/')),
                ('yayinlanma_tarihi', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Fotograflar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('double_sided', models.CharField(max_length=20)),
                ('color_option', models.CharField(max_length=20)),
                ('binding_option', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sayfa_sayisi', models.IntegerField(null=True)),
                ('deneme', models.IntegerField(null=True)),
                ('dosya', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Resim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('resim_dosyasi', models.ImageField(upload_to='resimler/')),
                ('fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.IntegerField()),
                ('spiral', models.CharField(max_length=5)),
                ('arkalik', models.CharField(max_length=20)),
                ('renk', models.CharField(max_length=20)),
                ('dosya', models.FileField(upload_to='siparisler/')),
                ('isim_soyisim', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=10)),
                ('resim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resim')),
            ],
        ),
    ]
