# Generated by Django 4.1.5 on 2023-04-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('fotograf', models.ImageField(upload_to='fotograflar/')),
                ('yayinlanma_tarihi', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
