# Generated by Django 4.2.2 on 2023-06-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siparis_notlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='notlar',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
