# Generated by Django 4.2.2 on 2023-06-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_siparis_notlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='cilt',
            field=models.CharField(default='Hiçbiri', max_length=20),
        ),
    ]
