# Generated by Django 4.1.5 on 2023-04-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fotograf_options_fotograf_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotograf',
            name='height',
        ),
        migrations.RemoveField(
            model_name='fotograf',
            name='width',
        ),
        migrations.AddField(
            model_name='resim',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
