# Generated by Django 4.1.5 on 2023-04-22 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_fotograf_height_remove_fotograf_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.IntegerField()),
                ('spiral', models.BooleanField()),
                ('arkalik', models.CharField(max_length=20)),
                ('renk', models.CharField(max_length=20)),
                ('dosya', models.FileField(upload_to='siparisler/')),
                ('resim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resim')),
            ],
        ),
    ]
