# Generated by Django 4.1.5 on 2023-04-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siparis'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='isim_soyisim',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siparis',
            name='telefon',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siparis',
            name='spiral',
            field=models.CharField(max_length=5),
        ),
    ]
