# Generated by Django 4.2.2 on 2023-06-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_siparis_spiral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='cilt',
            field=models.CharField(default='yok', max_length=20),
        ),
    ]
