# Generated by Django 4.1.5 on 2023-04-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siparis_isim_soyisim_siparis_telefon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='notlar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
