# Generated by Django 4.1.5 on 2023-04-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siparis_notlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='isim_soyisim',
            field=models.IntegerField(max_length=40),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='telefon',
            field=models.IntegerField(max_length=10),
        ),
    ]
