# Generated by Django 4.1.5 on 2023-04-26 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_siparis_isim_soyisim_alter_siparis_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='telefon',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Telefon numarası 10 haneli olmalıdır.')]),
        ),
    ]
