# Generated by Django 4.1.5 on 2023-04-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_siparis_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='telefon',
            field=models.CharField(max_length=15),
        ),
    ]
