# Generated by Django 4.1.5 on 2023-06-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_siparis_telefon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siparis',
            name='dosya',
        ),
        migrations.AddField(
            model_name='siparis',
            name='dosya',
            field=models.ManyToManyField(related_name='siparis_dosyalari', to='core.resim'),
        ),
    ]
