# Generated by Django 4.1.5 on 2023-06-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_siparis_dosya_siparis_dosya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siparis',
            name='dosya',
        ),
        migrations.AddField(
            model_name='siparis',
            name='dosya',
            field=models.FileField(default=None, upload_to='siparisler/'),
            preserve_default=False,
        ),
    ]
