# Generated by Django 4.1.5 on 2023-06-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sayfa_sayisi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='double_sided',
            field=models.CharField(max_length=20),
        ),
    ]
